name: printeasy_utils
description: "A Flutter package that contains utilities for PrintEasy Store and Admin"
repository: https://github.com/PrintEasy/PrintEasyUtils
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  flutter_web_plugins:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: ^0.20.1
  plugin_platform_interface: ^2.0.2
  screenshot: ^3.0.0
  shimmer: ^3.0.0
  syncfusion_flutter_barcodes: ^28.1.36
  web: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.printeasy_utils
        pluginClass: PrinteasyUtilsPlugin
      ios:
        pluginClass: PrinteasyUtilsPlugin
      web:
        pluginClass: PrinteasyUtilsWeb
        fileName: printeasy_utils_web.dart

  assets:
    - assets/images/
    - assets/svg/
