name: printeasy_utils
description: "A Flutter package that contains utilities for PrintEasy Store and Admin"
repository: https://github.com/PrintEasy/PrintEasyUtils
version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  flutter_web_plugins:
    sdk: flutter
  get: ^4.7.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  screenshot: ^3.0.0
  shimmer: ^3.0.0
  syncfusion_flutter_barcodes: ^29.1.39

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.printeasy_utils
        pluginClass: PrinteasyUtilsPlugin
      ios:
        pluginClass: PrinteasyUtilsPlugin

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Asteroid
      fonts:
        - asset: assets/fonts/Asteroid.ttf

    - family: BeachBikini
      fonts:
        - asset: assets/fonts/BeachBikini.ttf

    - family: Beachside
      fonts:
        - asset: assets/fonts/Beachside.ttf

    - family: BeachSunrise
      fonts:
        - asset: assets/fonts/BeachSunrise.ttf

    - family: BlueberryMuffin
      fonts:
        - asset: assets/fonts/BlueberryMuffin.ttf

    - family: Cakepop
      fonts:
        - asset: assets/fonts/Cakepop.ttf

    - family: California
      fonts:
        - asset: assets/fonts/California.ttf

    - family: DearMay
      fonts:
        - asset: assets/fonts/DearMay.ttf

    - family: Firefly
      fonts:
        - asset: assets/fonts/Firefly.ttf

    - family: Forever
      fonts:
        - asset: assets/fonts/Forever.ttf

    - family: FreshLemonade
      fonts:
        - asset: assets/fonts/FreshLemonade.ttf

    - family: Frozen
      fonts:
        - asset: assets/fonts/Frozen.ttf

    - family: Hathway
      fonts:
        - asset: assets/fonts/Hathway.ttf

    - family: HeySugar
      fonts:
        - asset: assets/fonts/HeySugar.ttf

    - family: Honey
      fonts:
        - asset: assets/fonts/Honey.ttf

    - family: Honeycomb
      fonts:
        - asset: assets/fonts/Honeycomb.ttf

    - family: However
      fonts:
        - asset: assets/fonts/However.ttf

    - family: IceCream
      fonts:
        - asset: assets/fonts/IceCream.ttf

    - family: Jade Skies
      fonts:
        - asset: assets/fonts/Jade Skies.ttf

    - family: Joyful
      fonts:
        - asset: assets/fonts/Joyful.ttf

    - family: Love Hearts
      fonts:
        - asset: assets/fonts/Love Hearts.ttf

    - family: Love More
      fonts:
        - asset: assets/fonts/Love More.ttf

    - family: Love Vibes
      fonts:
        - asset: assets/fonts/Love Vibes.ttf

    - family: LoveAndHoney
      fonts:
        - asset: assets/fonts/LoveAndHoney.ttf

    - family: MapleSugar
      fonts:
        - asset: assets/fonts/MapleSugar.ttf

    - family: Meanwhile
      fonts:
        - asset: assets/fonts/Meanwhile.ttf

    - family: Monkey
      fonts:
        - asset: assets/fonts/Monkey.ttf

    - family: MoreLove
      fonts:
        - asset: assets/fonts/MoreLove.ttf

    - family: Pink Rose
      fonts:
        - asset: assets/fonts/Pink Rose.ttf

    - family: RainbowDreams
      fonts:
        - asset: assets/fonts/RainbowDreams.ttf

    - family: Reality
      fonts:
        - asset: assets/fonts/Reality.ttf

    - family: Scramble
      fonts:
        - asset: assets/fonts/Scramble.ttf

    - family: Somekind
      fonts:
        - asset: assets/fonts/Somekind.ttf

    - family: SourSlushy
      fonts:
        - asset: assets/fonts/SourSlushy.ttf

    - family: SummerSunshine
      fonts:
        - asset: assets/fonts/SummerSunshine.ttf

    - family: Sunlight
      fonts:
        - asset: assets/fonts/Sunlight.ttf

    - family: SweetDreams
      fonts:
        - asset: assets/fonts/SweetDreams.ttf

    - family: TheWildOne
      fonts:
        - asset: assets/fonts/TheWildOne.ttf

    - family: TheWildOneFun
      fonts:
        - asset: assets/fonts/TheWildOneFun.ttf

    - family: TheWildOneSolid
      fonts:
        - asset: assets/fonts/TheWildOneSolid.ttf

    - family: Thinker
      fonts:
        - asset: assets/fonts/Thinker.ttf

    - family: Thoughtful
      fonts:
        - asset: assets/fonts/Thoughtful.ttf

    - family: TigerLand
      fonts:
        - asset: assets/fonts/TigerLand.ttf

    - family: Tigerlily
      fonts:
        - asset: assets/fonts/Tigerlily.ttf
